name: Validate JSON files

on:
  pull_request:
    branches: [master]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate JSON files
        run: |
          npm install -g jsonlint
          for file in $(find . -name "*.json"); do
            if jsonlint -q $file; then
              echo "Validation successful: $file"
            else
              echo "Validation failed: $file"
              exit 1
            fi
          done
      - name: Validate JSON file space
        run: |
          if [ ! -f "validators/list.json" ]; then
            echo "File not found!"
            exit 1
          fi

          if ! jq empty validators/list.json > /dev/null 2>&1; then
            echo "Invalid JSON file!"
            exit 1
          fi

          if grep -qE '\"[[:space:]]+|\"[[:space:]]+$|:\s+\"|,\s+\"' validators/list.json; then
            echo "JSON file contains values with leading or trailing spaces!"
            exit 1
          fi
